# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1439302974);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 29);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.search.countryCode", "CH");
user_pref("browser.search.region", "CH");
user_pref("browser.slowStartup.averageTime", 4807);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"langpack-de@iceweasel.mozilla.org\":{\"version\":\"39.0.3\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-de@iceweasel.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-GB@iceweasel.mozilla.org\":{\"version\":\"39.0.3\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-en-GB@iceweasel.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-es-AR@iceweasel.mozilla.org\":{\"version\":\"39.0.3\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-es-AR@iceweasel.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-es-ES@iceweasel.mozilla.org\":{\"version\":\"39.0.3\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-es-ES@iceweasel.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-fr@iceweasel.mozilla.org\":{\"version\":\"39.0.3\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-fr@iceweasel.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-it@iceweasel.mozilla.org\":{\"version\":\"39.0.3\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-it@iceweasel.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-pt-BR@iceweasel.mozilla.org\":{\"version\":\"39.0.3\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-pt-BR@iceweasel.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-ru@iceweasel.mozilla.org\":{\"version\":\"39.0.3\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-ru@iceweasel.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-sq@iceweasel.mozilla.org\":{\"version\":\"39.0.3\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-sq@iceweasel.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:39.0.3");
user_pref("extensions.lastAppVersion", "39.0.3");
user_pref("extensions.lastPlatformVersion", "39.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-de@iceweasel.mozilla.org\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/langpack-de@iceweasel.mozilla.org.xpi\",\"e\":true,\"v\":\"39.0.3\",\"st\":1438912653000},\"langpack-en-GB@iceweasel.mozilla.org\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/langpack-en-GB@iceweasel.mozilla.org.xpi\",\"e\":true,\"v\":\"39.0.3\",\"st\":1438912663000},\"langpack-es-AR@iceweasel.mozilla.org\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/langpack-es-AR@iceweasel.mozilla.org.xpi\",\"e\":true,\"v\":\"39.0.3\",\"st\":1438912673000},\"langpack-es-ES@iceweasel.mozilla.org\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/langpack-es-ES@iceweasel.mozilla.org.xpi\",\"e\":true,\"v\":\"39.0.3\",\"st\":1438912680000},\"langpack-fr@iceweasel.mozilla.org\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/langpack-fr@iceweasel.mozilla.org.xpi\",\"e\":true,\"v\":\"39.0.3\",\"st\":1438912703000},\"langpack-it@iceweasel.mozilla.org\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/langpack-it@iceweasel.mozilla.org.xpi\",\"e\":true,\"v\":\"39.0.3\",\"st\":1438912749000},\"langpack-pt-BR@iceweasel.mozilla.org\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/langpack-pt-BR@iceweasel.mozilla.org.xpi\",\"e\":true,\"v\":\"39.0.3\",\"st\":1438912815000},\"langpack-ru@iceweasel.mozilla.org\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/langpack-ru@iceweasel.mozilla.org.xpi\",\"e\":true,\"v\":\"39.0.3\",\"st\":1438912829000},\"langpack-sq@iceweasel.mozilla.org\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/langpack-sq@iceweasel.mozilla.org.xpi\",\"e\":true,\"v\":\"39.0.3\",\"st\":1438912846000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"39.0.3\",\"st\":1439231219000,\"mt\":1438915428000}}}");
user_pref("gecko.buildID", "20150807000803");
user_pref("gecko.mstone", "39.0.3");
user_pref("media.gmp-manager.buildID", "20150807000803");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 48929);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("security.disable_button.openCertManager", false);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1439302852);
user_pref("toolkit.telemetry.previousBuildID", "20150807000803");
